package gophermon

// Pokemon is a struct containing pokemon id and name.
type Pokemon struct {
	Id   uint64
	Name string
}

// Pokedex is exactly what it sounds like.
type Pokedex map[uint64]Pokemon

// Pokedex creates a Pokedex containing the first 151 Pokémon with their english names.
func GetPokedex() Pokedex {
	var data = []Pokemon{
		{Id: 1, Name: "Bulbasaur"},
		{Id: 2, Name: "Ivysaur"},
		{Id: 3, Name: "Venusaur"},
		{Id: 4, Name: "Charmander"},
		{Id: 5, Name: "Charmeleon"},
		{Id: 6, Name: "Charizard"},
		{Id: 7, Name: "Squirtle"},
		{Id: 8, Name: "Wartortle"},
		{Id: 9, Name: "Blastoise"},
		{Id: 10, Name: "Caterpie"},
		{Id: 11, Name: "Metapod"},
		{Id: 12, Name: "Butterfree"},
		{Id: 13, Name: "Weedle"},
		{Id: 14, Name: "Kakuna"},
		{Id: 15, Name: "Beedrill"},
		{Id: 16, Name: "Pidgey"},
		{Id: 17, Name: "Pidgeotto"},
		{Id: 18, Name: "Pidgeot"},
		{Id: 19, Name: "Rattata"},
		{Id: 20, Name: "Raticate"},
		{Id: 21, Name: "Spearow"},
		{Id: 22, Name: "Fearow"},
		{Id: 23, Name: "Ekans"},
		{Id: 24, Name: "Arbok"},
		{Id: 25, Name: "Pikachu"},
		{Id: 26, Name: "Raichu"},
		{Id: 27, Name: "Sandshrew"},
		{Id: 28, Name: "Sandslash"},
		{Id: 29, Name: "Nidoran (female)"},
		{Id: 30, Name: "Nidorina"},
		{Id: 31, Name: "Nidoqueen"},
		{Id: 32, Name: "Nidoran (male)"},
		{Id: 33, Name: "Nidorino"},
		{Id: 34, Name: "Nidoking"},
		{Id: 35, Name: "Clefairy"},
		{Id: 36, Name: "Clefable"},
		{Id: 37, Name: "Vulpix"},
		{Id: 38, Name: "Ninetales"},
		{Id: 39, Name: "Jigglypuff"},
		{Id: 40, Name: "Wigglytuff"},
		{Id: 41, Name: "Zubat"},
		{Id: 42, Name: "Golbat"},
		{Id: 43, Name: "Oddish"},
		{Id: 44, Name: "Gloom"},
		{Id: 45, Name: "Vileplume"},
		{Id: 46, Name: "Paras"},
		{Id: 47, Name: "Parasect"},
		{Id: 48, Name: "Venonat"},
		{Id: 49, Name: "Venomoth"},
		{Id: 50, Name: "Diglett"},
		{Id: 51, Name: "Dugtrio"},
		{Id: 52, Name: "Meowth"},
		{Id: 53, Name: "Persian"},
		{Id: 54, Name: "Psyduck"},
		{Id: 55, Name: "Golduck"},
		{Id: 56, Name: "Mankey"},
		{Id: 57, Name: "Primeape"},
		{Id: 58, Name: "Growlithe"},
		{Id: 59, Name: "Arcanine"},
		{Id: 60, Name: "Poliwag"},
		{Id: 61, Name: "Poliwhirl"},
		{Id: 62, Name: "Poliwrath"},
		{Id: 63, Name: "Abra"},
		{Id: 64, Name: "Kadabra"},
		{Id: 65, Name: "Alakazam"},
		{Id: 66, Name: "Machop"},
		{Id: 67, Name: "Machoke"},
		{Id: 68, Name: "Machamp"},
		{Id: 69, Name: "Bellsprout"},
		{Id: 70, Name: "Weepinbell"},
		{Id: 71, Name: "Victreebel"},
		{Id: 72, Name: "Tentacool"},
		{Id: 73, Name: "Tentacruel"},
		{Id: 74, Name: "Geodude"},
		{Id: 75, Name: "Graveler"},
		{Id: 76, Name: "Golem"},
		{Id: 77, Name: "Ponyta"},
		{Id: 78, Name: "RapIdash"},
		{Id: 79, Name: "Slowpoke"},
		{Id: 80, Name: "Slowbro"},
		{Id: 81, Name: "Magnemite"},
		{Id: 82, Name: "Magneton"},
		{Id: 83, Name: "Farfetch'd"},
		{Id: 84, Name: "Doduo"},
		{Id: 85, Name: "Dodrio"},
		{Id: 86, Name: "Seel"},
		{Id: 87, Name: "Dewgong"},
		{Id: 88, Name: "Grimer"},
		{Id: 89, Name: "Muk"},
		{Id: 90, Name: "Shellder"},
		{Id: 91, Name: "Cloyster"},
		{Id: 92, Name: "Gastly"},
		{Id: 93, Name: "Haunter"},
		{Id: 94, Name: "Gengar"},
		{Id: 95, Name: "Onix"},
		{Id: 96, Name: "Drowzee"},
		{Id: 97, Name: "Hypno"},
		{Id: 98, Name: "Krabby"},
		{Id: 99, Name: "Kingler"},
		{Id: 100, Name: "Voltorb"},
		{Id: 101, Name: "Electrode"},
		{Id: 102, Name: "Exeggcute"},
		{Id: 103, Name: "Exeggutor"},
		{Id: 104, Name: "Cubone"},
		{Id: 105, Name: "Marowak"},
		{Id: 106, Name: "Hitmonlee"},
		{Id: 107, Name: "Hitmonchan"},
		{Id: 108, Name: "Lickitung"},
		{Id: 109, Name: "Koffing"},
		{Id: 110, Name: "Weezing"},
		{Id: 111, Name: "Rhyhorn"},
		{Id: 112, Name: "Rhydon"},
		{Id: 113, Name: "Chansey"},
		{Id: 114, Name: "Tangela"},
		{Id: 115, Name: "Kangaskhan"},
		{Id: 116, Name: "Horsea"},
		{Id: 117, Name: "Seadra"},
		{Id: 118, Name: "Goldeen"},
		{Id: 119, Name: "Seaking"},
		{Id: 120, Name: "Staryu"},
		{Id: 121, Name: "Starmie"},
		{Id: 122, Name: "Mr."},
		{Id: 123, Name: "Scyther"},
		{Id: 124, Name: "Jynx"},
		{Id: 125, Name: "Electabuzz"},
		{Id: 126, Name: "Magmar"},
		{Id: 127, Name: "Pinsir"},
		{Id: 128, Name: "Tauros"},
		{Id: 129, Name: "Magikarp"},
		{Id: 130, Name: "Gyarados"},
		{Id: 131, Name: "Lapras"},
		{Id: 132, Name: "Ditto"},
		{Id: 133, Name: "Eevee"},
		{Id: 134, Name: "Vaporeon"},
		{Id: 135, Name: "Jolteon"},
		{Id: 136, Name: "Flareon"},
		{Id: 137, Name: "Porygon"},
		{Id: 138, Name: "Omanyte"},
		{Id: 139, Name: "Omastar"},
		{Id: 140, Name: "Kabuto"},
		{Id: 141, Name: "Kabutops"},
		{Id: 142, Name: "Aerodactyl"},
		{Id: 143, Name: "Snorlax"},
		{Id: 144, Name: "Articuno"},
		{Id: 145, Name: "Zapdos"},
		{Id: 146, Name: "Moltres"},
		{Id: 147, Name: "Dratini"},
		{Id: 148, Name: "Dragonair"},
		{Id: 149, Name: "Dragonite"},
		{Id: 150, Name: "Mewtwo"},
		{Id: 151, Name: "Mew"},
	}

	pokedex := make(Pokedex)
	for _, p := range data {
		pokedex[p.Id] = p
	}
	return pokedex
}
